---
- hosts: localhost
  vars:
    config_dir: configs
    base_temp_dir: copy-config
    env: test
    s3_config_bucket: dds-{{ env }}-personal-testing-bucket
    aws_region: eu-west-2
  vars_files:
    - vars/encrypted-vars.yml
  tasks:
    - name: Ensure Temporary directories are absent
      file:
        path: "{{ base_temp_dir }}"
        state: absent
    - name: Create top level directory
      file:
        path: "{{ base_temp_dir }}"
        state: directory
    - name: Create new config directories
      file:
        path: "{{ base_temp_dir }}/{{ item.path }}"
        state: directory
        mode: '{{ item.mode }}'
      with_filetree: "{{ config_dir }}"
      when: item.state == 'directory'
    - name: Template config files into new directories
      template:
        src: "{{ item.src }}"
        dest: "{{ base_temp_dir }}/{{ item.path }}"
      with_filetree: "{{ config_dir }}"
      when: item.state == 'file'
    - name: Upload directory
      s3_sync:
        bucket: "{{ s3_config_bucket }}"
        file_root: "{{ config_dir }}"
        key_prefix: "{{ config_dir }}"
        region: "{{ aws_region }}"
        delete: yes
    - name: Delete created temporary directories
      file:
        path: "{{ base_temp_dir }}"
        state: absent

